### ISSUE TITLE
Possible Feature: Global `--grep` option for basic filtering on results

### ISSUE THREAD

**Issue by sirosen** [globusonline/globus-cli#1]
@bd4, @corpulentcoffee: I'm particularly interested in your opinions on this, as we've had a number of discussions about the CLI design/layout.
Thoughts and opinions from everyone and anyone welcome, of course.

There's a potential feature that I'd like to think about and ask questions about.
For now, I'm calling it `--grep` because I think it's the most intuitive name for it, but I'm not thinking of doing full regex matching necessarily.
`--grep` is probably a _bad_ name for this if I add it, since it promises too much, but I don't have a good name yet. Maybe `--cli-filter`

Right now, a lot of commands have grep-friendly text output.
I'm going to use bookmark list for a bunch of examples because it has very simple output.

```shell
$ globus transfer bookmark list -Ftext
Name                             | Endpoint ID                          | Bookmark ID                          | Path
-------------------------------- | ------------------------------------ | ------------------------------------ | ----
Crummy Bookmark                  | d1763b75-6d04-11e5-ba46-22000b92c6ec | 6c0a7d14-f796-11e5-a6f9-22000bf2d559 | /abc/123/
EP1 GoData                       | ddb59aef-6d04-11e5-ba46-22000b92c6ec | ec207bf4-eb91-11e5-9829-22000b9da45e | /share/godata/
Test Bookmark Creation           | d1763b75-6d04-11e5-ba46-22000b92c6ec | 46e4d1b8-f78e-11e5-a6f9-22000bf2d559 | /abc/123/
```

In the case of commands like this, it's natural to want to be able to filter on columns in some way. My beloved `awk` can do great things here with `|` as its delimiter, and plain `grep` without column awareness is pretty useful too.
```shell
$ globus transfer bookmark list -Ftext | grep 'ec207bf4-eb91-11e5-9829-22000b9da45e'
EP1 GoData                       | ddb59aef-6d04-11e5-ba46-22000b92c6ec | ec207bf4-eb91-11e5-9829-22000b9da45e | /share/godata/
```
is a decent example of what we'll see people doing.

This really doesn't work well on the JSON output, however, for obvious reasons:
```shell
$ globus transfer bookmark list -Fjson | grep 'ec207bf4-eb91-11e5-9829-22000b9da45e' 
      "id": "ec207bf4-eb91-11e5-9829-22000b9da45e"
```

Now, what if that filtering were done inside of the CLI code itself, so instead of `globus ... | grep <expr>`, we had `globus ... --grep <expr>`?
We could apply that expression to text and JSON output uniformly -- quick and easy filtering for your results.

```shell
$ globus transfer bookmark list -Ftext --grep 'EP1'
EP1 GoData                       | ddb59aef-6d04-11e5-ba46-22000b92c6ec | ec207bf4-eb91-11e5-9829-22000b9da45e | /share/godata/
```
and importantly
```shell
$ globus transfer bookmark list -Fjson --grep 'EP1'
{
  "DATA": [
    {
      "name": "EP1 GoData", 
      "path": "/share/godata/", 
      "endpoint_id": "ddb59aef-6d04-11e5-ba46-22000b92c6ec", 
      "DATA_TYPE": "bookmark", 
      "id": "ec207bf4-eb91-11e5-9829-22000b9da45e"
    }
  ]
}
```

Bookmark list is not a very compelling case for this because it's small.
Endpoint Search obviously has searching and filtering options available in the API.

The three really strong cases for this feature, I think, are Task List, Event List, and ACL List.
Lots of people will want to do something like this:
```shell
$ globus transfer task list | grep 'Globus Tutorial Endpoint 1'
c44056b6-f075-11e5-9833-22000b9da45e | SUCCEEDED  | DELETE     | Globus Tutorial Endpoint 1       | None                             | globus-cli delete
b8a53d98-ed29-11e5-982b-22000b9da45e | SUCCEEDED  | TRANSFER   | Globus Tutorial Endpoint 1       | Globus Tutorial Endpoint 1       | None 
```
or this
```shell
$ globus transfer acl list --endpoint-id d1763b75-6d04-11e5-ba46-22000b92c6ec | grep 'identity'             
02ed6f8c-d2aa-11e5-9759-22000b9da45e | identity         | c8aad43e-d274-11e5-bf98-8b02896cf782 | rw          | /otherusers/globusteam/
02ed6f85-d2aa-11e5-9759-22000b9da45e | identity         | c8aad43e-d274-11e5-bf98-8b02896cf782 | r           | /   
01bbeadd-d2aa-11e5-9759-22000b9da45e | identity         | ae2f7f60-d274-11e5-b879-afc598dd59d4 | rw          | /otherusers/ballen/
None                                 | identity         | c8aad43e-d274-11e5-bf98-8b02896cf782 | rw          | / 
```

The easy way to start on this is a raw substring match on the SDK's `str(GlobusResponse)`
Then we can *maybe* do regex, and *maybe* only match on fields inside of a JSON structure, and *maybe* only apply on visible columns in text output.

I know that there's a case for saying that "Oh, no! We don't want people using Display Name in scripts!", but I don't think that's the only consideration here.
I recognize that there's a danger in allowing someone to do `globus transfer task list --grep <display_name> --format JSON > somefile.json`, but I don't think that's particularly hard to do on your own regardless.

The question, in my mind, is whether or not some kind of basic filtering -- insufficient for all needs but useful in small doses -- would be a useful thing to have in the CLI.
If we just do a substring match on `str(GlobusResponse)`, the implementation and maintenance cost is very cheap.
Is substring match not good enough? Should we do full regexes?

Is this entire idea an unnecessary feature?
We can always tell people to use `grep` or `jq`.
They'll certainly have the former, but not everyone has a command-line JSON filtering tool at the ready.
Although this *might* be useful for text output, I'm more interested in supporting simple filtering on JSON out. OTOH, maybe just instructing people in the use of `jq` (my personal favorite) is good enough?

**Comment by corpulentcoffee** [comment]
If I were a casual user of your CLI, I likely would not bother to learn your tool-specific `grep`-like flags and I would just use a `globus <whatever> | grep <whatever>` pipeline. If I needed more context with JSON output and I were using the tool interactively, I would just sloppily add `-U10` and be perfectly happy with that.

And even if I were using the JSON output in a script, as long as I already knew about the `jq` tool, I would more likely find what I needed from `man jq` to formulate `globus transfer bookmark list -Fjson | jq '.DATA[] | select(.name | contains("EP1"))'` on my own to get exactly what I want instead of fumbling around with any `globus`-specific flags.

And besides that, it seems like for this to work, you would need to know about what all the envelopes look like for all the API responses to intelligently apply a filter to them.

**Comment by bd4** [comment]
I think this is a speculative feature that is not worth adding now. Even users really do end up using JSON a lot, we can point them at jq as Dave suggested, and if for some reason that doesn't satisfy all the use cases, we can explore adding some sort of feature. But it's not clear what would be useful that can't be provided by piping to standard tools at this point.

**Comment by sirosen** [comment]
I agree that this was speculative.
I was sitting in a coffee shop this weekend and the idea struck as something maybe-useful.

Given that you guys aren't enthusiastic about the idea, I'm closing this out.
For a cosmetic feature like this, genuine enthusiasm would be necessary for me to add it.
